# Generated by Django 3.1.3 on 2020-12-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20201210_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchpost',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('permitted', 'Permitted'), ('disallowed', 'Disallowed')], default='pending', max_length=30),
        ),
    ]
