# Generated by Django 3.1.3 on 2020-12-11 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_auto_20201211_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepost',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
    ]
