# Generated by Django 3.1.3 on 2020-12-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_auto_20201211_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchpostreply',
            name='detail',
        ),
        migrations.AddField(
            model_name='batchpostreply',
            name='content',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
