# Generated by Django 3.1.3 on 2020-12-11 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_auto_20201211_1359'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseImage',
            new_name='CoursePostImage',
        ),
    ]
