# Generated by Django 3.1.3 on 2020-12-12 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_auto_20201211_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepostimage',
            name='post',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='course.coursepost'),
        ),
    ]
