# Generated by Django 3.1.3 on 2020-12-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_auto_20201212_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepostimage',
            name='img',
            field=models.ImageField(null=True, upload_to='coursepost_image/'),
        ),
    ]
