# Generated by Django 3.1.3 on 2020-12-12 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_auto_20201212_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchPostFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(null=True, upload_to='batchpost_file/')),
                ('post', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='course.batchpost')),
            ],
        ),
        migrations.CreateModel(
            name='CoursePostFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='coursepost_file/')),
                ('post', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='course.coursepost')),
            ],
        ),
        migrations.DeleteModel(
            name='CoursePostImage',
        ),
    ]
