# Generated by Django 3.1.3 on 2020-12-12 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_auto_20201212_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batchpostfile',
            old_name='img',
            new_name='file',
        ),
    ]
