# Generated by Django 3.1.3 on 2020-12-13 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_auto_20201212_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batchpostreply',
            old_name='batchpost',
            new_name='post',
        ),
    ]
