# Generated by Django 3.1.3 on 2021-02-25 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_auto_20210110_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepostfile',
            name='post',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='coursefile', to='course.coursepost'),
        ),
    ]
