# Generated by Django 3.1.3 on 2021-07-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0024_auto_20210709_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepost',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
