# Generated by Django 3.1.3 on 2021-07-13 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0025_coursepost_date_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursepost',
            old_name='date_modified',
            new_name='date_updated',
        ),
    ]
