# Generated by Django 3.1.3 on 2021-07-13 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0029_remove_batchpost_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchpost',
            name='batch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='course.batch'),
        ),
    ]
