# Generated by Django 3.1.2 on 2020-10-28 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Posts',
        ),
    ]
