# Generated by Django 3.1.3 on 2020-12-07 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0010_group_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='group.group'),
        ),
    ]
