# Generated by Django 3.1.3 on 2020-12-07 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0012_auto_20201207_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='time_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ManyToManyField(to='group.Group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
