# Generated by Django 3.1.3 on 2020-12-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0015_auto_20201207_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='group',
            field=models.ManyToManyField(blank=True, to='group.Group'),
        ),
    ]
