# Generated by Django 3.1.3 on 2020-12-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0016_auto_20201207_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='group',
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, to='group.Member'),
        ),
    ]
