# Generated by Django 3.1.3 on 2020-12-10 03:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0023_auto_20201210_1112'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='GroupPost',
        ),
    ]
