# Generated by Django 3.1.3 on 2020-12-10 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0024_auto_20201210_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='batchpost',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='student',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.DeleteModel(
            name='BatchPost',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
