# Generated by Django 3.1.3 on 2020-12-10 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0025_auto_20201210_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouppost',
            old_name='dated_posted',
            new_name='date_posted',
        ),
    ]
