# Generated by Django 3.1.3 on 2021-07-16 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0031_auto_20201214_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppost',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='grouppostfile',
            name='post',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='groupfile', to='group.grouppost'),
        ),
    ]
