# Generated by Django 3.1.3 on 2021-07-16 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0032_auto_20210716_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppost',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='group.group'),
        ),
    ]
