# Generated by Django 3.1.3 on 2021-07-18 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0035_auto_20210718_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppostcomment',
            name='comment_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
