# Generated by Django 3.1.3 on 2020-12-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_auto_20201223_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementfile',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='announcement_thumbnail/'),
        ),
    ]
