# Generated by Django 3.1.3 on 2021-01-04 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_announcementfile_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcementfile',
            name='thumbnail',
        ),
    ]
