# Generated by Django 3.1.3 on 2021-07-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0004_remove_announcementfile_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(blank=True, max_length=650, null=True),
        ),
    ]
